// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 23.1 (Build Build 991 11/28/2023)
// Created on Thu Feb 15 01:20:20 2024

lr3 lr3_inst
(
	.c(c_sig) ,	// input  c_sig
	.Q0(Q0_sig) ,	// output  Q0_sig
	.Q1(Q1_sig) ,	// output  Q1_sig
	.Q2(Q2_sig) ,	// output  Q2_sig
	.Q3(Q3_sig) ,	// output  Q3_sig
	.Q4(Q4_sig) 	// output  Q4_sig
);

